# Generated by Django 4.1.5 on 2023-02-25 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('companyname', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='companyimage')),
                ('description', models.CharField(max_length=100)),
                ('companysignup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companysignup', to='app.companysignup')),
            ],
        ),
    ]
