# Generated by Django 4.1.5 on 2023-02-26 02:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('noofdays', models.IntegerField()),
                ('departuredate', models.DateField()),
                ('createddate', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(upload_to='tripimage')),
                ('description', models.CharField(max_length=400)),
                ('status', models.BooleanField(default=False)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='app.company')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province', to='app.province')),
            ],
        ),
    ]
