# Generated by Django 4.1.5 on 2023-02-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_trip_description_alter_trip_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutIMG1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='aboutimg2')),
            ],
        ),
        migrations.CreateModel(
            name='AboutIMG2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='aboutimg2')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField()),
                ('no_of_completed_tours', models.IntegerField()),
                ('no_of_destinations', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceIMG1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='experienceimg2')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceIMG2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='experienceimg2')),
            ],
        ),
        migrations.CreateModel(
            name='HomeIMG1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homeimg1')),
            ],
        ),
        migrations.CreateModel(
            name='HomeIMG2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homeimg2')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='video')),
            ],
        ),
    ]
