# Generated by Django 4.1.5 on 2023-02-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_aboutimg1_aboutimg2_experiencecount_experienceimg1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.FileField(upload_to='video'),
        ),
    ]
