# Generated by Django 4.1.5 on 2023-02-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_video_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='image',
            new_name='video',
        ),
    ]
