# Generated by Django 4.1.5 on 2023-02-26 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_image_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='provinces'),
            preserve_default=False,
        ),
    ]
