# Generated by Django 4.1.5 on 2023-02-27 18:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_usersignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('persons', models.IntegerField()),
                ('message', models.CharField(max_length=250)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='app.trip')),
                ('usersignup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersignup_id', to='app.usersignup')),
            ],
        ),
    ]
