# Generated by Django 4.1.5 on 2023-02-27 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='companysignup_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Companysignup_id', to='app.companysignup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=10),
        ),
    ]
