# Generated by Django 4.1.5 on 2023-03-02 08:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_order_companysignup_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10)),
                ('stars', models.DecimalField(decimal_places=2, max_digits=2)),
                ('feedback', models.CharField(max_length=250)),
                ('feedback_date', models.DateField(default=datetime.date.today)),
                ('usersignup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usignup_id', to='app.usersignup')),
            ],
        ),
    ]
