# Generated by Django 4.1.5 on 2023-03-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_feedback_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review',
            field=models.BooleanField(default=False),
        ),
    ]
